title: port
description: Exploring low power wireless sensor networks with practical everyday things
url: "https://avinashpudale.github.io"
markdown: kramdown
permalink: /:title
youtube: https://www.youtube.com/user/sweska/videos
github:
  repository_url: https://github.com/AvinashPudale
exclude: [
  _tutorials/*.h,
  # _tutorials/*.html, # used for html demo code page
  _tutorials/*.ino,
  # _tutorials/*.js, # used for html demo code page
  _tutorials/*.json,
  _tutorials/*Makefile,
  CNAME,
  Gemfile,
  Gemfile.lock,
  LICENSE.md,
  Makefile,
  README.md
]
collections:
  tutorials:
    output: true
    permalink: /tutorials/:name
  checklists:
    output: true
    permalink: /port/:name
    
