title: Hutscape
description: Exploring low power wireless sensor networks with practical everyday things
url: "https://hutscape.com"
markdown: kramdown
permalink: /:title
google_analytics: UA-144008567-1
github:
  repository_url: https://github.com/hutscape/hutscape.github.io
collections:
  components:
    output: true
    permalink: /components/:name
  checklists:
    output: true
    permalink: /checklists/:name
  references:
    output: true
