title: Hutscape
description: Exploring wireless sensor networks with everyday things
url: "https://hutscape.com"
markdown: kramdown
permalink: /:title
google_analytics: UA-XXXXX-Y
collections:
  components:
    output: true
    permalink: /components/:name
  checklists:
    output: true
    permalink: /checklists/:name
  references:
    output: true
